// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an operator within a diff, with enough context to display it.
 */
export type DiffOperatorRef = { id: string, label: string, operator_type_name: string | null, plan_id: string | null, };
