// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Representative subset of the Kaggle "Car Price Dataset" schema.
 *
 * Source columns: Brand, Model, Year, Engine_Size, Fuel_Type, Transmission,
 * Mileage, Doors, Owner_Count, Price.
 *
 * The data is bundled in-source so the POC has zero runtime dependencies on
 * the Quent backend or any external HTTP fetch.
 */

export interface CarRow {
  Brand: string;
  Model: string;
  Year: number;
  Engine_Size: number;
  Fuel_Type: 'Petrol' | 'Diesel' | 'Hybrid' | 'Electric';
  Transmission: 'Manual' | 'Automatic' | 'Semi-Automatic';
  Mileage: number;
  Doors: number;
  Owner_Count: number;
  Price: number;
}

export const CAR_COLUMNS: ReadonlyArray<keyof CarRow> = [
  'Brand',
  'Model',
  'Year',
  'Engine_Size',
  'Fuel_Type',
  'Transmission',
  'Mileage',
  'Doors',
  'Owner_Count',
  'Price',
];

export const NUMERIC_CAR_COLUMNS: ReadonlyArray<keyof CarRow> = [
  'Year',
  'Engine_Size',
  'Mileage',
  'Doors',
  'Owner_Count',
  'Price',
];

export const CAR_ROWS: ReadonlyArray<CarRow> = [
  {
    Brand: 'Toyota',
    Model: 'Corolla',
    Year: 2018,
    Engine_Size: 1.8,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 42000,
    Doors: 4,
    Owner_Count: 1,
    Price: 14500,
  },
  {
    Brand: 'Toyota',
    Model: 'Corolla',
    Year: 2020,
    Engine_Size: 1.8,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 22000,
    Doors: 4,
    Owner_Count: 1,
    Price: 18900,
  },
  {
    Brand: 'Toyota',
    Model: 'RAV4',
    Year: 2019,
    Engine_Size: 2.5,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 35000,
    Doors: 5,
    Owner_Count: 2,
    Price: 24500,
  },
  {
    Brand: 'Toyota',
    Model: 'RAV4',
    Year: 2021,
    Engine_Size: 2.5,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 12000,
    Doors: 5,
    Owner_Count: 1,
    Price: 31200,
  },
  {
    Brand: 'Toyota',
    Model: 'Camry',
    Year: 2017,
    Engine_Size: 2.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 58000,
    Doors: 4,
    Owner_Count: 2,
    Price: 16200,
  },
  {
    Brand: 'Toyota',
    Model: 'Camry',
    Year: 2022,
    Engine_Size: 2.5,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 8000,
    Doors: 4,
    Owner_Count: 1,
    Price: 28900,
  },
  {
    Brand: 'Honda',
    Model: 'Civic',
    Year: 2016,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 72000,
    Doors: 4,
    Owner_Count: 3,
    Price: 11500,
  },
  {
    Brand: 'Honda',
    Model: 'Civic',
    Year: 2019,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 31000,
    Doors: 4,
    Owner_Count: 1,
    Price: 18200,
  },
  {
    Brand: 'Honda',
    Model: 'Civic',
    Year: 2021,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 14000,
    Doors: 4,
    Owner_Count: 1,
    Price: 21500,
  },
  {
    Brand: 'Honda',
    Model: 'Accord',
    Year: 2018,
    Engine_Size: 2.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 48000,
    Doors: 4,
    Owner_Count: 2,
    Price: 17200,
  },
  {
    Brand: 'Honda',
    Model: 'Accord',
    Year: 2020,
    Engine_Size: 2.0,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 19000,
    Doors: 4,
    Owner_Count: 1,
    Price: 24800,
  },
  {
    Brand: 'Honda',
    Model: 'CR-V',
    Year: 2019,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 41000,
    Doors: 5,
    Owner_Count: 2,
    Price: 21900,
  },
  {
    Brand: 'Honda',
    Model: 'CR-V',
    Year: 2022,
    Engine_Size: 1.5,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 9000,
    Doors: 5,
    Owner_Count: 1,
    Price: 30500,
  },
  {
    Brand: 'Ford',
    Model: 'Focus',
    Year: 2015,
    Engine_Size: 1.6,
    Fuel_Type: 'Diesel',
    Transmission: 'Manual',
    Mileage: 89000,
    Doors: 5,
    Owner_Count: 3,
    Price: 8900,
  },
  {
    Brand: 'Ford',
    Model: 'Focus',
    Year: 2018,
    Engine_Size: 1.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 52000,
    Doors: 5,
    Owner_Count: 2,
    Price: 12900,
  },
  {
    Brand: 'Ford',
    Model: 'Fiesta',
    Year: 2017,
    Engine_Size: 1.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 64000,
    Doors: 5,
    Owner_Count: 2,
    Price: 9800,
  },
  {
    Brand: 'Ford',
    Model: 'Fiesta',
    Year: 2020,
    Engine_Size: 1.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 21000,
    Doors: 5,
    Owner_Count: 1,
    Price: 14200,
  },
  {
    Brand: 'Ford',
    Model: 'Mustang',
    Year: 2019,
    Engine_Size: 5.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 18000,
    Doors: 2,
    Owner_Count: 1,
    Price: 39800,
  },
  {
    Brand: 'Ford',
    Model: 'Mustang',
    Year: 2021,
    Engine_Size: 5.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 7000,
    Doors: 2,
    Owner_Count: 1,
    Price: 48500,
  },
  {
    Brand: 'Ford',
    Model: 'Explorer',
    Year: 2020,
    Engine_Size: 3.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 28000,
    Doors: 5,
    Owner_Count: 1,
    Price: 35200,
  },
  {
    Brand: 'BMW',
    Model: '320i',
    Year: 2017,
    Engine_Size: 2.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 55000,
    Doors: 4,
    Owner_Count: 2,
    Price: 19800,
  },
  {
    Brand: 'BMW',
    Model: '320i',
    Year: 2020,
    Engine_Size: 2.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 22000,
    Doors: 4,
    Owner_Count: 1,
    Price: 31500,
  },
  {
    Brand: 'BMW',
    Model: '530i',
    Year: 2018,
    Engine_Size: 3.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 41000,
    Doors: 4,
    Owner_Count: 2,
    Price: 32500,
  },
  {
    Brand: 'BMW',
    Model: '530i',
    Year: 2021,
    Engine_Size: 3.0,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 12000,
    Doors: 4,
    Owner_Count: 1,
    Price: 49800,
  },
  {
    Brand: 'BMW',
    Model: 'X3',
    Year: 2019,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 38000,
    Doors: 5,
    Owner_Count: 2,
    Price: 34200,
  },
  {
    Brand: 'BMW',
    Model: 'X5',
    Year: 2020,
    Engine_Size: 3.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 31000,
    Doors: 5,
    Owner_Count: 1,
    Price: 49500,
  },
  {
    Brand: 'BMW',
    Model: 'i3',
    Year: 2019,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 24000,
    Doors: 4,
    Owner_Count: 1,
    Price: 22500,
  },
  {
    Brand: 'BMW',
    Model: 'i4',
    Year: 2022,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 6000,
    Doors: 4,
    Owner_Count: 1,
    Price: 51200,
  },
  {
    Brand: 'Mercedes',
    Model: 'C-Class',
    Year: 2017,
    Engine_Size: 2.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 52000,
    Doors: 4,
    Owner_Count: 2,
    Price: 22800,
  },
  {
    Brand: 'Mercedes',
    Model: 'C-Class',
    Year: 2020,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 26000,
    Doors: 4,
    Owner_Count: 1,
    Price: 34900,
  },
  {
    Brand: 'Mercedes',
    Model: 'E-Class',
    Year: 2018,
    Engine_Size: 3.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 44000,
    Doors: 4,
    Owner_Count: 2,
    Price: 35800,
  },
  {
    Brand: 'Mercedes',
    Model: 'E-Class',
    Year: 2021,
    Engine_Size: 3.0,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 13000,
    Doors: 4,
    Owner_Count: 1,
    Price: 52400,
  },
  {
    Brand: 'Mercedes',
    Model: 'GLC',
    Year: 2019,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 36000,
    Doors: 5,
    Owner_Count: 2,
    Price: 38700,
  },
  {
    Brand: 'Mercedes',
    Model: 'EQC',
    Year: 2021,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 9000,
    Doors: 5,
    Owner_Count: 1,
    Price: 58200,
  },
  {
    Brand: 'Volkswagen',
    Model: 'Golf',
    Year: 2016,
    Engine_Size: 1.4,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 78000,
    Doors: 5,
    Owner_Count: 3,
    Price: 9800,
  },
  {
    Brand: 'Volkswagen',
    Model: 'Golf',
    Year: 2019,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 32000,
    Doors: 5,
    Owner_Count: 1,
    Price: 16400,
  },
  {
    Brand: 'Volkswagen',
    Model: 'Golf',
    Year: 2021,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 14000,
    Doors: 5,
    Owner_Count: 1,
    Price: 21800,
  },
  {
    Brand: 'Volkswagen',
    Model: 'Passat',
    Year: 2017,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 61000,
    Doors: 4,
    Owner_Count: 2,
    Price: 14500,
  },
  {
    Brand: 'Volkswagen',
    Model: 'Passat',
    Year: 2020,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 25000,
    Doors: 4,
    Owner_Count: 1,
    Price: 22900,
  },
  {
    Brand: 'Volkswagen',
    Model: 'Tiguan',
    Year: 2018,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 47000,
    Doors: 5,
    Owner_Count: 2,
    Price: 19800,
  },
  {
    Brand: 'Volkswagen',
    Model: 'ID.4',
    Year: 2022,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 6000,
    Doors: 5,
    Owner_Count: 1,
    Price: 41200,
  },
  {
    Brand: 'Audi',
    Model: 'A3',
    Year: 2017,
    Engine_Size: 1.4,
    Fuel_Type: 'Petrol',
    Transmission: 'Semi-Automatic',
    Mileage: 49000,
    Doors: 5,
    Owner_Count: 2,
    Price: 18200,
  },
  {
    Brand: 'Audi',
    Model: 'A3',
    Year: 2020,
    Engine_Size: 1.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Semi-Automatic',
    Mileage: 21000,
    Doors: 5,
    Owner_Count: 1,
    Price: 26400,
  },
  {
    Brand: 'Audi',
    Model: 'A4',
    Year: 2018,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 43000,
    Doors: 4,
    Owner_Count: 2,
    Price: 22800,
  },
  {
    Brand: 'Audi',
    Model: 'A4',
    Year: 2021,
    Engine_Size: 2.0,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 12000,
    Doors: 4,
    Owner_Count: 1,
    Price: 36900,
  },
  {
    Brand: 'Audi',
    Model: 'Q5',
    Year: 2019,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 37000,
    Doors: 5,
    Owner_Count: 1,
    Price: 32500,
  },
  {
    Brand: 'Audi',
    Model: 'Q7',
    Year: 2020,
    Engine_Size: 3.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 28000,
    Doors: 5,
    Owner_Count: 1,
    Price: 48900,
  },
  {
    Brand: 'Audi',
    Model: 'e-tron',
    Year: 2021,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 11000,
    Doors: 5,
    Owner_Count: 1,
    Price: 62500,
  },
  {
    Brand: 'Hyundai',
    Model: 'i30',
    Year: 2017,
    Engine_Size: 1.4,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 56000,
    Doors: 5,
    Owner_Count: 2,
    Price: 9200,
  },
  {
    Brand: 'Hyundai',
    Model: 'i30',
    Year: 2020,
    Engine_Size: 1.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 22000,
    Doors: 5,
    Owner_Count: 1,
    Price: 14800,
  },
  {
    Brand: 'Hyundai',
    Model: 'Tucson',
    Year: 2018,
    Engine_Size: 1.6,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 41000,
    Doors: 5,
    Owner_Count: 2,
    Price: 16500,
  },
  {
    Brand: 'Hyundai',
    Model: 'Tucson',
    Year: 2021,
    Engine_Size: 1.6,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 13000,
    Doors: 5,
    Owner_Count: 1,
    Price: 24700,
  },
  {
    Brand: 'Hyundai',
    Model: 'Kona',
    Year: 2020,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 19000,
    Doors: 5,
    Owner_Count: 1,
    Price: 26800,
  },
  {
    Brand: 'Kia',
    Model: 'Ceed',
    Year: 2018,
    Engine_Size: 1.4,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 44000,
    Doors: 5,
    Owner_Count: 2,
    Price: 11200,
  },
  {
    Brand: 'Kia',
    Model: 'Ceed',
    Year: 2021,
    Engine_Size: 1.4,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 17000,
    Doors: 5,
    Owner_Count: 1,
    Price: 17800,
  },
  {
    Brand: 'Kia',
    Model: 'Sportage',
    Year: 2019,
    Engine_Size: 1.6,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 38000,
    Doors: 5,
    Owner_Count: 2,
    Price: 18900,
  },
  {
    Brand: 'Kia',
    Model: 'Sportage',
    Year: 2022,
    Engine_Size: 1.6,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 8000,
    Doors: 5,
    Owner_Count: 1,
    Price: 27500,
  },
  {
    Brand: 'Kia',
    Model: 'EV6',
    Year: 2022,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 5000,
    Doors: 5,
    Owner_Count: 1,
    Price: 49800,
  },
  {
    Brand: 'Tesla',
    Model: 'Model 3',
    Year: 2019,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 28000,
    Doors: 4,
    Owner_Count: 1,
    Price: 32500,
  },
  {
    Brand: 'Tesla',
    Model: 'Model 3',
    Year: 2021,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 14000,
    Doors: 4,
    Owner_Count: 1,
    Price: 41200,
  },
  {
    Brand: 'Tesla',
    Model: 'Model 3',
    Year: 2023,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 3000,
    Doors: 4,
    Owner_Count: 1,
    Price: 47800,
  },
  {
    Brand: 'Tesla',
    Model: 'Model Y',
    Year: 2021,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 12000,
    Doors: 5,
    Owner_Count: 1,
    Price: 51800,
  },
  {
    Brand: 'Tesla',
    Model: 'Model Y',
    Year: 2023,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 4000,
    Doors: 5,
    Owner_Count: 1,
    Price: 58900,
  },
  {
    Brand: 'Tesla',
    Model: 'Model S',
    Year: 2020,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 18000,
    Doors: 4,
    Owner_Count: 1,
    Price: 71200,
  },
  {
    Brand: 'Nissan',
    Model: 'Micra',
    Year: 2017,
    Engine_Size: 1.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 51000,
    Doors: 5,
    Owner_Count: 2,
    Price: 7800,
  },
  {
    Brand: 'Nissan',
    Model: 'Qashqai',
    Year: 2018,
    Engine_Size: 1.5,
    Fuel_Type: 'Diesel',
    Transmission: 'Manual',
    Mileage: 49000,
    Doors: 5,
    Owner_Count: 2,
    Price: 14200,
  },
  {
    Brand: 'Nissan',
    Model: 'Qashqai',
    Year: 2021,
    Engine_Size: 1.3,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 16000,
    Doors: 5,
    Owner_Count: 1,
    Price: 22800,
  },
  {
    Brand: 'Nissan',
    Model: 'Leaf',
    Year: 2019,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 25000,
    Doors: 5,
    Owner_Count: 1,
    Price: 17800,
  },
  {
    Brand: 'Nissan',
    Model: 'Leaf',
    Year: 2022,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 8000,
    Doors: 5,
    Owner_Count: 1,
    Price: 26500,
  },
  {
    Brand: 'Mazda',
    Model: 'Mazda3',
    Year: 2018,
    Engine_Size: 2.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 39000,
    Doors: 4,
    Owner_Count: 2,
    Price: 14800,
  },
  {
    Brand: 'Mazda',
    Model: 'Mazda3',
    Year: 2021,
    Engine_Size: 2.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 15000,
    Doors: 4,
    Owner_Count: 1,
    Price: 21500,
  },
  {
    Brand: 'Mazda',
    Model: 'CX-5',
    Year: 2019,
    Engine_Size: 2.5,
    Fuel_Type: 'Petrol',
    Transmission: 'Automatic',
    Mileage: 34000,
    Doors: 5,
    Owner_Count: 2,
    Price: 22800,
  },
  {
    Brand: 'Mazda',
    Model: 'CX-5',
    Year: 2022,
    Engine_Size: 2.5,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 9000,
    Doors: 5,
    Owner_Count: 1,
    Price: 31900,
  },
  {
    Brand: 'Volvo',
    Model: 'XC40',
    Year: 2020,
    Engine_Size: 2.0,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 21000,
    Doors: 5,
    Owner_Count: 1,
    Price: 36800,
  },
  {
    Brand: 'Volvo',
    Model: 'XC60',
    Year: 2019,
    Engine_Size: 2.0,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 32000,
    Doors: 5,
    Owner_Count: 2,
    Price: 31500,
  },
  {
    Brand: 'Volvo',
    Model: 'XC90',
    Year: 2021,
    Engine_Size: 2.0,
    Fuel_Type: 'Hybrid',
    Transmission: 'Automatic',
    Mileage: 14000,
    Doors: 5,
    Owner_Count: 1,
    Price: 58400,
  },
  {
    Brand: 'Peugeot',
    Model: '208',
    Year: 2019,
    Engine_Size: 1.2,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 28000,
    Doors: 5,
    Owner_Count: 1,
    Price: 11900,
  },
  {
    Brand: 'Peugeot',
    Model: '308',
    Year: 2018,
    Engine_Size: 1.6,
    Fuel_Type: 'Diesel',
    Transmission: 'Manual',
    Mileage: 47000,
    Doors: 5,
    Owner_Count: 2,
    Price: 12500,
  },
  {
    Brand: 'Peugeot',
    Model: '3008',
    Year: 2020,
    Engine_Size: 1.5,
    Fuel_Type: 'Diesel',
    Transmission: 'Automatic',
    Mileage: 22000,
    Doors: 5,
    Owner_Count: 1,
    Price: 24800,
  },
  {
    Brand: 'Renault',
    Model: 'Clio',
    Year: 2017,
    Engine_Size: 0.9,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 58000,
    Doors: 5,
    Owner_Count: 2,
    Price: 8800,
  },
  {
    Brand: 'Renault',
    Model: 'Clio',
    Year: 2020,
    Engine_Size: 1.0,
    Fuel_Type: 'Petrol',
    Transmission: 'Manual',
    Mileage: 24000,
    Doors: 5,
    Owner_Count: 1,
    Price: 13200,
  },
  {
    Brand: 'Renault',
    Model: 'Megane',
    Year: 2018,
    Engine_Size: 1.5,
    Fuel_Type: 'Diesel',
    Transmission: 'Manual',
    Mileage: 52000,
    Doors: 5,
    Owner_Count: 2,
    Price: 11800,
  },
  {
    Brand: 'Renault',
    Model: 'Zoe',
    Year: 2021,
    Engine_Size: 0.0,
    Fuel_Type: 'Electric',
    Transmission: 'Automatic',
    Mileage: 12000,
    Doors: 5,
    Owner_Count: 1,
    Price: 22500,
  },
];

export function isNumericColumn(col: keyof CarRow): boolean {
  return (NUMERIC_CAR_COLUMNS as ReadonlyArray<string>).includes(col as string);
}
